CONFIG = {
    'FACEBOOK_TOKEN': 'EAAbrMRr7dV0BAC6yvPXrQhd3tZChHE1fYuFJ1EzfGJZAUHkgNRZAfUHkkPC8oGZAtOJ66kHZCGVQboL4Suwij4QzIiFtZB40hoIUdMuHlGzWBxwBZBlw6g9wvtVCWg2xZCyk36RMlgjZAZAQxxQBASp9XlRzAZAWGNEZCrzJw0bTssbZAxAZDZD',
    'VERIFY_TOKEN': 'verify_hodorbot',
    'SERVER_URL': 'https://e8b6b06c.ngrok.io'
}